#!/bin/bash

IMAGE=$1
OUTPUT=$2

if [[ ! $(command -v convert) ]]; then
	echo "Need to install Imagemagick"
fi

# Uncomment for OSX
# convert $IMAGE -resize 128x128^> $OUTPUT

# Uncomment for Linux
convert $IMAGE -resize 128x128\> $OUTPUT
